spring:
  datasource:
    username: root
    password: 123456
    #url: jdbc:mysql://192.168.84.88:3306/gulimall_ums?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://101.200.200.220:3306/gulimall_ums?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: gulimall-member
  thymeleaf:
    cache: false
  session:
    store-type: redis
  cloud:
    nacos:
      discovery:
        server-addr: 101.200.200.220:8848
       # server-addr: 192.168.84.88:8848
    sentinel:
      transport:
        dashboard: localhost:8333
        port: 8719

  redis:
    host: 192.168.84.88
    port: 6379
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      #调整主键自增
      id-type: auto
server:
  port: 8000
#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
management:
  endpoints:
    web:
      exposure:
        include: '*'