spring:
  application:
    name: gulimall-seckill
  thymeleaf:
    cache: false
  rabbitmq:
      host: 192.168.84.88
      port: 5672
      virtual-host: /
      #发送端确认
      publisher-confirm-type: correlated
      #发送端消息抵达队列确认
      publisher-returns: true
      #只要抵达队列，以异步方式优先回调returnConfirm
      template:
        mandatory: true
      #手动确认消息
      listener:
        simple:
          acknowledge-mode: manual
  redis:
    host: 192.168.84.88
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 101.200.200.220:8848
#  task:
#    scheduling:
#      pool:
#        size: 5
  task:
    execution:
      pool:
        core-size: 20
        max-size: 50
  session:
    store-type: redis


server:
  port: 25000


#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
