
spring:
  datasource:
    username: root
    password: 123456
   # url: jdbc:mysql://192.168.84.88:3306/gulimall_sms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://101.200.200.220:3306/gulimall_sms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: gulimall-coupon
  cloud:
    nacos:
      discovery:
        #server-addr: 192.168.84.88:8848 #Nacos服务注册中心地址
        server-addr: 101.200.200.220:8848 #Nacos服务注册中心地址

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      #调整主键自增
      id-type: auto
server:
  port: 7000
