spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 101.200.200.220:8848
  redis:
    host: 101.200.200.220
    port: 6379
  thymeleaf:
    cache: false
server:
  port: 20000

