server:
  port: 9000
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://101.200.200.220:3306/gulimall_oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.84.88
    port: 5672
    virtual-host: /
    #发送端确认
    publisher-confirm-type: correlated
    #发送端消息抵达队列确认
    publisher-returns: true
    #只要抵达队列，以异步方式优先回调returnConfirm
    template:
      mandatory: true
    #手动确认消息
    listener:
      simple:
        acknowledge-mode: manual
  redis:
    host: 192.168.84.88
  cloud:
    nacos:
      discovery:
        server-addr: 101.200.200.220:8848
  application:
    name: gulimall-order
  session:
    store-type: redis
  mvc:
    format:
      date: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      #调整主键自增
      id-type: auto


 #支付宝支付
alipay:
  app_id: 2021000119659403
  notify_url: http://5003186h7t.qicp.vip/order/alipay/success
  return_url: http://member.guli-mall.com/member-order.html
  sign_type: RSA2
  charset: utf-8
  gatewayUrl: https://openapi.alipaydev.com/gateway.do
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA25m81POB6eLr/W3nXttMU1p7vZKoGFPMKur3VCmcQDvAuq1Nrd43gZIWn+v/JcaOvtfixUooBTeMQiVTcp2J8MWlf3zFRao7j9QVIWjvDSg4lX9kRHfVQxmOAvZQNAX/aRLN4id9jhp+2jFqVpqgz9efClFE7+ycX4MvqyjiGV0K2flMa9Zxn4cixm/PlFEu8WFUZ0fFO4odE7JTxZT1/nbF3IEXeJ60RMHy+XU2n+XNgEI0hW6vjPJKXOoiYAQsBxrZI38Y4kLKz2oT6OtgG4aqe/RVbN7lEcW+tPmizBkLt8uIauMIb+cJBwBuPCcBrOKvLS6ick4bu9FTypmgswIDAQAB
  merchant-private-key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDKY1T5fkZomY2obogQKHRaB7cxd/6k9pL+gwLnvBRxw1t9RfIjOmZ0e5ocucTEUPZlGTCYNKb2TH2jl7GmnsYx1X8Sw++r7ObLputgHB03VCn4gca/wiwmu2Xj9qgbZdWbM3CfcZGKOQ7pEsMPY+Kxt3iZFLBRYYO5kC/TyMchdCBh/F2srKYryE4advgFh144nVLl9RZ1x8NHaOSAFMeMDws/62AtQT9+48IyZ+3xiGQDr0uCP4hGqeOcWFiiJGoZluF80tDYW0oD1NFSpJ+7o8B0EQiHabG9yVoE6w06DmwUla9NDjWCHkxT9bsGYUahIW+UPJcAtVPh372PdA6LAgMBAAECggEADmJ0/a6d7n1Ldjc08IEPk/6MZLW0oaDs3a4OHM5fXZ6W+BZqmVpjQdAvKe+CLrnaaWEa9RZ473SMUX5MoB0U1SHpgDnw5PVXig35GMGmyfHvcbw3lhWE8dPL8CHt3NSmE/vZ+1slDv/zMVmmB4f/6sWxip/P0Fjv9dZrr8/LZ3MrJdVxegBcDhiIlYxLyTMed3+4C6bEGt2DaRe7RrsU4CSKa6mRNDxYeUdC3uokpPG5XWnzrLsrBeyRX/taK0jP1/hSlG+mJ0B1kaI1XHkA0u+0Z3R7BWKiSimEbAnu7dL3qd3F35l6LlnTAEnWsUqYrE3mxGkblCf804W8d/9PIQKBgQDnE8s9iTlG0/cOguy5cMctvfxtp9fiaz5mRqQWz1BJHtTtZNPYviisitzww45pKuo9KRixuLGbX6AOTkLDM3yxpVKBvUh56SWhWhMzlum2nkTYb71N5zDtj0jGe2wOKQYTr7qGSPt1LhcccdBPjwzprCedSBrXGuXYzS8y42KcMwKBgQDgN2gDQq0vuSw5NlLh1m6l8qYyVH4qKzQNKz6So47D8A/ggpu2mYyb4JXsdpkhdbKUYUahVYtNBWX7vwpdHniA5wNFp+U1sIW+iCIuBM5Lfrq5dSonV7HN6661vwG+/1dnoHZ9P3cCSepQab1F6/34HLwZLXiyFqNZeQOj99BsSQKBgHOjnzkrXAOK/f9AG/Ftc+/7PMEvlsUTgEW0oldb5kTBbjNjGvVDrJ00XP8MDk+pD1IOJ/KAiDlGMJYYKib/tC4+mrycmhGQUKmfpy5RHqKqL6/Us3qx8PVhmDzj9R5c/1KIxaKAEX8B0sUEXAgEgaTK54Q5Wl09c7r8a9tembGrAoGAThz/b6NbErVAYu46EdPS2J2gqQgmrCpBCBV4xz2UD08jOORHu2XjRqsHkEoBL1cB0A/Tu4FB9qNa1EnKIobrFH1m9m13vSyya56hycaC2GpeQx4+gVZb65GgXFEfGpt6p++PWDM0EugNadZsyl9dK4NXRK5Czkh0wEcYrZc4VYECgYB1yIrXX7sQOodM3HJJeE9P7wvt5pYjaJ13wyNcIbGK+8fkiNp/y2pijPX4c2KGA5vlcAgixOwlRjcJ1cXP93ywT1cHvr9FxcJolW63mbLfY0mp5yP2xaHN0BVeCAwAEpa4fSvJ0JdmHS31ZpTuCu3tukLP8kTdLPzExhDFBZqJQQ==
  timeout: 30





#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000

