server:
  port: 9000


spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://101.200.200.220:3306/gulimall_oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      #调整主键自增
      id-type: auto