spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: 101.200.200.220:8848
  thymeleaf:
    cache: false
  redis:
    port: 6379
    host: 192.168.84.88
server:
  port: 12000
