spring:
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: lb://gulimall-product
          predicates:
              - Path=/api/product/**, /hello
          filters:
              - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: third_party_route
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: member_route
          uri: lb://gulimall-member
          predicates:
              - Path=/api/member/**
          filters:
              - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: member_route
          uri: lb://gulimall-warehouse
          predicates:
              - Path=/api/ware/**
          filters:
              - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: coupon_route
          uri: lb://gulimall-coupon
          predicates:
              - Path=/api/coupon/**
          filters:
              - RewritePath=/api/(?<segment>.*), /$\{segment}

        - id: gulimall_auth_route
          uri: lb://gulimall-auth-server
          predicates:
            - Host=auth.guli-mall.com
        - id: gulimall_cart_route
          uri: lb://gulimall-cart
          predicates:
              - Host=cart.guli-mall.com
        - id: gulimall_order_route
          uri: lb://gulimall-order
          predicates:
              - Host=order.guli-mall.com
        - id: gulimall_member_route
          uri: lb://gulimall-member
          predicates:
              - Host=member.guli-mall.com
        - id: gulimall_host
          uri: lb://gulimall-product
          predicates:
              - Host=guli-mall.com,item.guli-mall.com
        - id: gulimall_search
          uri: lb://gulimall-search
          predicates:
            - Host=search.guli-mall.com
        - id: gulimall_secondkill
          uri: lb://gulimall-seckill
          predicates:
            - Host=seckill.guli-mall.com
        - id: admin_route
          uri: lb://renren-fast

          predicates:
            - Path=/api/**
          filters:
             - RewritePath=/api/(?<segment>.*), /renren-fast/$\{segment}



