global:
  scrape_interval:     60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: prometheus

  - job_name: linux
    static_configs:
      - targets: ['101.200.200.220:9100']
        labels:
          instance: localhost

  - job_name: mysql
    static_configs:
      - targets: ['101.200.200.220:9104']
        labels:
          instance: mysql