spring:
  cloud:
    nacos:
      discovery:
        server-addr: 101.200.200.220:8848
        #server-addr: 192.168.84.88:8848
    sentinel:
      transport:
        dashboard: localhost:8333
        port: 8719

  application:
    name: gulimall-third-party
    #阿里云短短信验证码
  alicloud:
    sms:
      appcode: f01b7961ffe44a368a07e593d1711561
      path: /sms/
      template-id: M72CB42894
      host: https://jumsendsms.market.alicloudapi.com

server:
  port: 30000
#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
management:
  endpoints:
    web:
      exposure:
        include: '*'