server:
  port: 40000
spring:
  application:
    name: gulimall-cart
  cloud:
    nacos:
      discovery:
        server-addr: 101.200.200.220:8848
    sentinel:
     transport:
      dashboard: localhost:8333
      port: 8719
  sleuth:
    sampler:
      probability: 1
  zipkin:
      base-url: http://192.168.84.88:9411/
      discovery-client-enabled: false
      sender:
        type: web
  redis:
    host: 192.168.84.88
    port: 6379
#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.sleuth: debug